// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CT Greebnsock', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CT Greebnsock', async function() {
    await driver.get("https://www.magazineluiza.com.br/")
    await driver.manage().window().setRect({ width: 974, height: 1032 })
    await driver.findElement(By.id("input-search")).click()
    await driver.findElement(By.css(".hvRRkp:nth-child(2) > .sc-kpDqfm")).click()
    {
      const element = await driver.findElement(By.linkText("Ofertas do Dia"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.executeScript("window.scrollTo(0,533)")
    await driver.findElement(By.css(".sc-SSKRe:nth-child(1) .sc-doohEh")).click()
    await driver.executeScript("window.scrollTo(0,350)")
    await driver.executeScript("window.scrollTo(0,346)")
    await driver.findElement(By.css(".sc-ePDLzJ")).click()
    await driver.findElement(By.id("input-search")).click()
    await driver.findElement(By.css(".hvRRkp:nth-child(4) > .sc-kpDqfm")).click()
    await driver.executeScript("window.scrollTo(0,377)")
    await driver.executeScript("window.scrollTo(0,667)")
    {
      const element = await driver.findElement(By.css(".sc-SSKRe:nth-child(3) > .sc-eBMEME"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.executeScript("window.scrollTo(0,667)")
    await driver.findElement(By.css(".sc-SSKRe:nth-child(4) .sc-feNupb > .sc-cWSHoV")).click()
    await driver.findElement(By.id("input-search")).click()
    await driver.findElement(By.css(".sc-dhKdcB:nth-child(6)")).click()
    {
      const element = await driver.findElement(By.css(".sc-SSKRe:nth-child(1) .sc-feNupb > .sc-cWSHoV"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.executeScript("window.scrollTo(0,127)")
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".sc-SSKRe:nth-child(3) .sc-cWSHoV")).click()
    await driver.executeScript("window.scrollTo(0,324)")
    await driver.executeScript("window.scrollTo(0,151)")
    await driver.findElement(By.css(".sc-cHMHOW")).click()
    await driver.findElement(By.css(".sc-dOvA-dm")).click()
    await driver.findElement(By.css(".sc-ePDLzJ")).click()
    await driver.findElement(By.id("input-search")).click()
    await driver.findElement(By.css(".hvRRkp:nth-child(3) > .sc-kpDqfm")).click()
    await driver.findElement(By.css(".sc-fqkvVR:nth-child(2) .sc-cWSHoV")).click()
    {
      const element = await driver.findElement(By.css(".sc-fqkvVR:nth-child(2) .sc-buvPDS"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.executeScript("window.scrollTo(0,400)")
    await driver.findElement(By.css(".sc-SSKRe:nth-child(1) .sc-lpYOg > .sc-dhKdcB")).click()
    await driver.executeScript("window.scrollTo(0,358)")
    await driver.executeScript("window.scrollTo(0,884)")
    await driver.close()
  })
})
