// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CT pontofrio', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CT pontofrio', async function() {
    await driver.get("https://carrinho.pontofrio.com.br/")
    await driver.manage().window().setRect({ width: 974, height: 1032 })
    await driver.findElement(By.id("logo_svg__Camada_1")).click()
    await driver.findElement(By.id("search-form-input")).click()
    await driver.findElement(By.id("search-form-input")).sendKeys("con")
    await driver.findElement(By.id("search-form-input")).click()
    await driver.findElement(By.id("search-form-input")).sendKeys("notebook")
    await driver.findElement(By.id("search-form-input")).sendKeys(Key.ENTER)
    await driver.executeScript("window.scrollTo(0,39)")
    await driver.findElement(By.id("search-form-input")).click()
    await driver.findElement(By.id("search-form-input")).sendKeys("fogao")
    await driver.findElement(By.id("search-form-input")).sendKeys(Key.DOWN)
    await driver.findElement(By.id("search-form-input")).sendKeys(Key.UP)
    await driver.findElement(By.id("search-form-input")).sendKeys(Key.ENTER)
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.id("search-form-input")).click()
    await driver.findElement(By.id("search-form-input")).sendKeys("alexa")
    await driver.findElement(By.id("search-form-input")).sendKeys(Key.ENTER)
    await driver.close()
  })
})
